In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [4]:
#Load Libraries for Data Analysis


import pandas as pd
import os
os.listdir('/kaggle/input/datasets/vincenthope/stock-prices/')

['Stock_Prices.csv']

In [5]:
data = pd.read_csv("/kaggle/input/datasets/vincenthope/stock-prices/Stock_Prices.csv")

data.head(5)

  symbol      date      open      high       low     close    volume
0    AAL  1/2/2014   25.0700   25.8200   25.0600   25.3600   8998943
1   AAPL  1/2/2014   79.3828   79.5756   78.8601   79.0185  58791957
2    AAP  1/2/2014  110.3600  111.8800  109.2900  109.7400    542711
3   ABBV  1/2/2014   52.1200   52.3300   51.5200   51.9800   4569061
4    ABC  1/2/2014   70.1100   70.2300   69.4800   69.8900   1148391

In [6]:
# Check for missing values (True/False)
data.isnull()

        symbol   date   open   high    low  close  volume
0        False  False  False  False  False  False   False
1        False  False  False  False  False  False   False
2        False  False  False  False  False  False   False
3        False  False  False  False  False  False   False
4        False  False  False  False  False  False   False
...        ...    ...    ...    ...    ...    ...     ...
497467   False  False  False  False  False  False   False
497468   False  False  False  False  False  False   False
497469   False  False  False  False  False  False   False
497470   False  False  False  False  False  False   False
497471   False  False  False  False  False  False   False

[497472 rows x 7 columns]

In [7]:
# Counting missing values per column
data.isnull().sum()

symbol     0
date       0
open      11
high       8
low        8
close      0
volume     0
dtype: int64

In [8]:
# Total missing values
data.isnull().sum().sum()

np.int64(27)

In [9]:
# Check How Many Records There Are 
data.shape

(497472, 7)

In [10]:
# Drop Rows With Missing Values Since Not Much i.e 27
data_clean = data.dropna()

# Check to see output 
data_clean.isnull().sum()

symbol    0
date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [11]:
# Check How Many Records Remain
data_clean.shape

(497461, 7)

In [12]:
# Check for Duplicates - Shows True for Duplicate Rows
data_clean.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
497467    False
497468    False
497469    False
497470    False
497471    False
Length: 497461, dtype: bool

In [13]:
# Check for No of Duplicates 
data_clean.duplicated().sum()

np.int64(0)

In [14]:
# Display first 10 Records

data_clean.head(10)

  symbol      date      open      high       low     close    volume
0    AAL  1/2/2014   25.0700   25.8200   25.0600   25.3600   8998943
1   AAPL  1/2/2014   79.3828   79.5756   78.8601   79.0185  58791957
2    AAP  1/2/2014  110.3600  111.8800  109.2900  109.7400    542711
3   ABBV  1/2/2014   52.1200   52.3300   51.5200   51.9800   4569061
4    ABC  1/2/2014   70.1100   70.2300   69.4800   69.8900   1148391
5    ABT  1/2/2014   38.0900   38.4000   38.0000   38.2300   4967472
6    ACN  1/2/2014   81.5000   81.9200   81.0900   81.1300   2405384
7   ADBE  1/2/2014   59.0600   59.5300   58.9400   59.2900   2746370
8    ADI  1/2/2014   49.5200   49.7500   49.0400   49.2800   2799092
9    ADM  1/2/2014   43.2200   43.2900   42.7900   42.9900   2753765

In [15]:
# Standardize Date Records
data_clean.loc[:, 'date'] = pd.to_datetime(data_clean['date'])

In [16]:
# Display first 10 Records

data_clean.head(10)

,symbol,date,open,high,low,close,volume
0,AAL,2014-01-02 00:00:00,25.0700,25.8200,25.0600,25.3600,8998943
1,AAPL,2014-01-02 00:00:00,79.3828,79.5756,78.8601,79.0185,58791957
2,AAP,2014-01-02 00:00:00,110.3600,111.8800,109.2900,109.7400,542711
3,ABBV,2014-01-02 00:00:00,52.1200,52.3300,51.5200,51.9800,4569061
4,ABC,2014-01-02 00:00:00,70.1100,70.2300,69.4800,69.8900,1148391
5,ABT,2014-01-02 00:00:00,38.0900,38.4000,38.0000,38.2300,4967472
6,ACN,2014-01-02 00:00:00,81.5000,81.9200,81.0900,81.1300,2405384
7,ADBE,2014-01-02 00:00:00,59.0600,59.5300,58.9400,59.2900,2746370
8,ADI,2014-01-02 00:00:00,49.5200,49.7500,49.0400,49.2800,2799092
9,ADM,2014-01-02 00:00:00,43.2200,43.2900,42.7900,42.9900,2753765

In [18]:
# Export Clean & Processed Data
# index = false : does not save row nos as columns 
data_clean.to_csv("Project1.csv", index=False)
print("Data saved successfully!")

data.to_csv("Cleaned_Dataset.csv", index=False)

Data saved successfully!